### PR TITLE
Do not automatically walk the filetree setting quotas

### PR DESCRIPTION
**Pull request by amitschang**
From the git logs, this seems to have been a workaround for a time when a version of compute created user volumes outside of the purview of the fileservice or quota manager, which seems not to be the case any more. We expect each volume is created with the cache, and this endpoint can still be called via the API with credentials. We may choose to remove it after a period of observation where it is no longer deemed necessary.

It is expected (hoped) that some pressure will be releived on the underlying filesystem with this change.

**NB**: please use hide whitespace changes, the real change is about 3 lines

### CODE REVIEW

**Review by glemson — APPROVED** [review]
seems right to me. cannot think of any reason other than what was mentioned for having this running.

**Comment by glemson** [comment]
btw, the title of this issue seems not to cover the change you made. it basically turns of scheduled quota checking/setting.
whereas the title indicates the quotas will not be set using a file tree walk.

**Comment by amitschang** [comment]
> btw, the title of this issue seems not to cover the change you made. it basically turns of scheduled quota checking/setting.
> whereas the title indicates the quotas will not be set using a file tree walk.

I changed it, the key here being we no longer automatically do this

**Comment by mtaghiza** [comment]
Is there an url for testing this?
The dashboard says that the "File usage information can take up to 30 minutes to first appear or update." How is removing the 30min automatic scheduling in applyQuotas() going to affect that? If it has no effect, was there a cause for placing that phrase in the dashboard? That phrase needs to be removed or modified if no longer applicable.

**Comment by amitschang** [comment]
I have not deployed this anywhere, would have to dig around to see where and how it is deployed but I assume there should be one associated with scitest12...

I believe the 30 minutes thing in the dashboard comes from the same reason this apply thing was there, to catch volumes created outside the quota manager. I think it would no longer have effect, and when the fileservice cache thing gets fixed, it would be more like 5 minutes (assuming the filesystem itself doesn't have some lag). we don't make any promises here though, so the language could stay or be removed, but wouldn't have to synchronize changes or anything.

**Comment by amitschang** [comment]
got another slack-based approval, so will merge

**Pull request merged**
